# Generated by Django 5.1.4 on 2025-01-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_chef_email_chef_phone_number_dish_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chef",
            options={"verbose_name": "Chef", "verbose_name_plural": "Chefs"},
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name": "Dish", "verbose_name_plural": "Dishes"},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"verbose_name": "Dish Type", "verbose_name_plural": "Dish Types"},
        ),
    ]
