# Generated by Django 5.1.4 on 2025-01-15 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_alter_chef_options_alter_dish_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
